### ISSUE TITLE
Ajustes no link do botão ver perfil e home[Corrigido]

### ISSUE THREAD

**Issue by oliveiralex** [danielbortolozo/github-user-search#1]
Caro Daniel,

Estou corrigindo seu trabalho do cap 2 do bootcamp. Seu trabalho foi aceito, parabéns! Para ficar 100%, peço que você faça os seguintes ajustes.

1. Na rota "/search", quando busco um usuário do gitHub, o mesmo está buscando corretamente. Porém, ao clicar no botão "ver perfil", o mesmo não está direcionando para o gitHub do usuário.

2. Outro problema é que ao clicar no link da barra superior "Bootcamp DevSuperior", não está direcionando para a tela home (rota: "/home").

Peço que você realize os ajustes e assim que finalizar me avise para que eu possa checar.

Abraço e bons estudos!

**Comment by danielbortolozo** [comment]
OK, já fiz as correções. Pode reavaliar.
